trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_Stage
  displayName:
  jobs:
  - job: BuildNuget
    displayName: Build Nuget packages
    variables:
      BuildConfiguration: release
    steps:

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        versioningScheme: 'off'
        
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        vstsFeed: 'MyLibrary--Nuget/MyLibrary---Nuget'
        publishVstsFeed: 'MyLibrary--Nuget/MyLibrary---Nuget'
        versioningScheme: 'off'
        allowPackageConflicts: true
